Fikir ve Öneriler Şablonu Düzenleme
fluxteam/IssueTracker pull request #27
Opened 2021-02-03 20:36 UTC by Zamion101

Hata Raporu Şablonu için yapılan düzenlemeler ekstra olarak Fikir ve Önerler şablonu içinde uygulanmıştır. Daha fazla geliştirilebilir.

2021-02-03 20:47 UTC, Teo00 requested changes
Yorumlarım belirtilmiştir.

2021-02-03 20:47 UTC, Teo00 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +about: Fikir ve Önerilerinizi bize bildirerek WordBot'un gelişmesinde sizde katkıda bulunun
Not just WordBot. Bots under FluxTeam.

2021-02-03 20:47 UTC, Teo00 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +- [ ] Daha önceden açılan Fikirleri/Önerileri kontrol ettim ve kendikime benzer bir Fikir/Öneri bulamadım. <!-- Köşeli parantezin içine 'X' yazınız -->
> kendikime (x) açacağım fikre/öneriye (*)

2021-02-03 20:47 UTC, Teo00 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +- [ ] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım. <!-- Köşeli parantezin içine 'X' yazınız -->
Hata alınıyorsa doldurulması gerektiği belirtilmeli.

2021-02-03 20:47 UTC, Teo00 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +bizim bu Fikir/Öneri hakkında daha fazla bir bilgi sahibi olmamıza
İSTEĞE BAĞLI: örnek yazılabilir

2021-02-03 22:25 UTC, ysfchn approved these changes
Bunun dışında herhangi bir sorun göremedim:

2021-02-03 22:25 UTC, ysfchn commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +<!-- Bu Fikrinize/Önerinize ait ekstra eklemek istediklernizi (Resim/Video/Konsept tasarımı gib) lütfen buraya ekleyiniz -->
Yazım yanlışı:
```suggestion
<!-- Bu fikrinize/önerinize ait ekstra eklemek istediklerinizi (Resim/Video/Konsept tasarımı gibi) lütfen buraya ekleyiniz -->
```

2021-02-03 22:45 UTC, Teo00 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +<!-- Bu Fikrinize/Önerinize ait ekstra eklemek istediklernizi (Resim/Video/Konsept tasarımı gib) lütfen buraya ekleyiniz -->
o zaman neden approve'luyorsunuz acaba 😕😏

2021-02-03 22:46 UTC, ysfchn commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +<!-- Bu Fikrinize/Önerinize ait ekstra eklemek istediklernizi (Resim/Video/Konsept tasarımı gib) lütfen buraya ekleyiniz -->
Çünkü çok kritik değil 😄

2021-02-09 19:40 UTC, Zamion101 commented on .github/ISSUE_TEMPLATE/fikir-ve--neriler.md
> +- [ ] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım. <!-- Köşeli parantezin içine 'X' yazınız -->
Gerekli olmadığı görüşündeyim zaten cümlenin kendisi bu durumu belirtiyor.

2021-02-09 20:43 UTC, ysfchn approved these changes

2021-02-09 20:52 UTC, Hagfog approved these changes

2021-02-10 01:29 UTC, Teo00 approved these changes
Uygundur.

2021-02-10 08:17 UTC, merged